### ISSUE TITLE
Difficulty Annotating Brain Organoid Sample Using HNOCA Dataset

### ISSUE THREAD

**Issue by nicola-palmieri** [theislab/neural_organoid_atlas#4]
Hello HNOCA Team,

I'm having trouble loading the HNOCA dataset into R for cell type annotation of my brain organoid samples. I've tried various packages (SingleR, BPCells), but the loading process doesn't complete, even after waiting 15 minutes. Is there a recommended method or package for efficiently loading the 40GB HNOCA dataset into R?

Thank you
Nicola

**Comment by zhisonghe** [comment]
Hi, Nicola,

Unfortunately the complete HNOCA dataset will be likely too large to be loaded as a whole in R, mostly because of the limitation on the sparse matrix non-zero item number there. If you think it is helpful we can generate an atlas subset for analysis on R.

All the best,
Zhisong

**Comment by nicola-palmieri** [comment]
That would be great! I also tried in many different ways in Python but did not manage. I am trying to characterize a dataset of brain organoids.

**Comment by zhisonghe** [comment]
Hi, Nicola,

Please check the RDS file of the following link and see whether it works: https://www.dropbox.com/scl/fi/eeobuu3nydxb10wm657uu/HNOCA_one-per-aggrecell.seurat.rds?rlkey=yv1iqyo5jryuh49ye1jt84mrm&st=1lzf68lc&dl=0. It will be uploaded to zenodo later if it works.

In brief, this is a Seurat object with the RNA assay in the v3 Assay object. It includes a subset of HNOCA, accounting for 515802 cells. The strategy to create this subset was to select one cell per aggrecell (see the Methods section of the paper). Please note that this is not a fully random subsampling, but instead a subsampling biased towards the datasets and protocols with fewer cells.

All the best,
Zhisong

**Comment by nicola-palmieri** [comment]
Thank you so much for sharing this. I’ve loaded the RDS file in R, and it works perfectly on my end. It’s amazing to have access to this subset of the HNOCA data! I’m very grateful for your efforts—it will be invaluable for annotating my brain organoid samples using data from other organoids.

Kind regards
Nicola
